export type AttachmentEntityType = 'customer' | 'supplier' | 'product' | 'sale' | 'purchase' | 'expense' | 'bill'
export interface Attachment { id: string; fileName: string; mimeType: string; size: number; uploadedAt: string }
const API_URL = import.meta.env.VITE_API_URL ?? 'http://localhost:4000/api'
function headers() { const value = new Headers({ 'Content-Type': 'application/json' }); const token = localStorage.getItem('pbb_auth_token'); if (token) value.set('Authorization', `Bearer ${token}`); return value }
async function request<T>(path: string, options: RequestInit = {}): Promise<T> { const response = await fetch(`${API_URL}${path}`, { ...options, headers: { ...Object.fromEntries(headers().entries()), ...(options.headers ? Object.fromEntries(new Headers(options.headers).entries()) : {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.message ?? 'Request failed.'); return body as T }
export function listAttachments(entityType: AttachmentEntityType, entityId: string): Promise<Attachment[]> { return request<Attachment[]>(`/attachments?entityType=${encodeURIComponent(entityType)}&entityId=${encodeURIComponent(entityId)}`) }
export async function uploadAttachment(entityType: AttachmentEntityType, entityId: string, file: File): Promise<Attachment> { if (file.size > 5 * 1024 * 1024) throw new Error('Files must be 5 MB or smaller.'); const data = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => { const value = String(reader.result ?? ''); const comma = value.indexOf(','); resolve(comma >= 0 ? value.slice(comma + 1) : value) }; reader.onerror = () => reject(new Error('Unable to read the selected file.')); reader.readAsDataURL(file) }); return request<Attachment>('/attachments', { method: 'POST', body: JSON.stringify({ entityType, entityId, fileName: file.name, mimeType: file.type || 'application/octet-stream', data }) }) }
export async function deleteAttachment(id: string): Promise<void> { await request<{ ok: true }>(`/attachments/${id}`, { method: 'DELETE' }) }
export async function openAttachment(id: string, fileName: string): Promise<void> { const token = localStorage.getItem('pbb_auth_token'); const response = await fetch(`${API_URL}/attachments/${id}`, { headers: token ? { Authorization: `Bearer ${token}` } : {} }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.message ?? 'Unable to open document.') } const blob = await response.blob(); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.target = '_blank'; anchor.rel = 'noopener'; anchor.download = fileName; document.body.appendChild(anchor); anchor.click(); anchor.remove(); setTimeout(() => URL.revokeObjectURL(url), 60_000) }
