import { Router } from 'express'
import { ObjectId } from 'mongodb'
import { getDb } from '../db.js'
import { recordAuditEvent } from '../audit.js'
import { requireAuth, type AuthenticatedRequest } from '../middleware.js'

export interface PurchaseRecord { _id: ObjectId; purchaseNumber: string; supplierId?: ObjectId; supplierName: string; supplierState: string; productId: ObjectId; productName: string; unit: string; quantity: number; unitPrice: number; subtotal: number; gstRate: number; gstType: 'none' | 'cgst_sgst' | 'igst'; cgstAmount: number; sgstAmount: number; igstAmount: number; taxAmount: number; totalAmount: number; createdByUserId: ObjectId; createdAt: Date }
export const purchasesRouter = Router(); purchasesRouter.use(requireAuth)
function round(value: number) { return Math.round(value * 100) / 100 }
function sanitizePurchase(purchase: PurchaseRecord) { return { id: purchase._id.toHexString(), purchaseNumber: purchase.purchaseNumber, supplierId: purchase.supplierId?.toHexString(), supplierName: purchase.supplierName, supplierState: purchase.supplierState, productId: purchase.productId.toHexString(), productName: purchase.productName, unit: purchase.unit, quantity: purchase.quantity, unitPrice: purchase.unitPrice, subtotal: purchase.subtotal, gstRate: purchase.gstRate, gstType: purchase.gstType, cgstAmount: purchase.cgstAmount, sgstAmount: purchase.sgstAmount, igstAmount: purchase.igstAmount, taxAmount: purchase.taxAmount, totalAmount: purchase.totalAmount, createdAt: purchase.createdAt } }
purchasesRouter.get('/', async (_req, res) => { const purchases = await getDb().collection<PurchaseRecord>('purchases').find({}).sort({ createdAt: -1 }).limit(100).toArray(); return res.json({ purchases: purchases.map(sanitizePurchase) }) })
purchasesRouter.post('/', async (req: AuthenticatedRequest, res) => {
  const body = req.body as Record<string, unknown> | null; const supplierId = typeof body?.supplierId === 'string' ? body.supplierId : ''; const legacySupplierName = typeof body?.supplierName === 'string' ? body.supplierName.trim() : ''; const supplierStateInput = typeof body?.supplierState === 'string' ? body.supplierState.trim() : ''; const productId = typeof body?.productId === 'string' ? body.productId : ''; const quantity = typeof body?.quantity === 'number' ? body.quantity : Number(body?.quantity); const unitPrice = typeof body?.unitPrice === 'number' ? body.unitPrice : Number(body?.unitPrice); const gstRate = typeof body?.gstRate === 'number' ? body.gstRate : Number(body?.gstRate ?? 0)
  if (!supplierId && !legacySupplierName) return res.status(400).json({ message: 'Supplier is required' }); if (supplierId && !ObjectId.isValid(supplierId)) return res.status(400).json({ message: 'Valid supplier is required' }); if (!ObjectId.isValid(productId)) return res.status(400).json({ message: 'Valid product is required' }); if (!Number.isFinite(quantity) || quantity <= 0) return res.status(400).json({ message: 'Quantity must be greater than zero' }); if (!Number.isFinite(unitPrice) || unitPrice < 0) return res.status(400).json({ message: 'Purchase price must be a valid non-negative number' }); if (!Number.isFinite(gstRate) || gstRate < 0 || gstRate > 28) return res.status(400).json({ message: 'GST rate must be between 0% and 28%' })
  const db = getDb(); const [product, settings, supplier] = await Promise.all([db.collection('products').findOne({ _id: new ObjectId(productId), isActive: true }), db.collection('business_settings').findOne({ _id: 'business' }), supplierId ? db.collection('suppliers').findOne({ _id: new ObjectId(supplierId), isActive: true }) : null])
  if (!product) return res.status(400).json({ message: 'Product is not active or does not exist' }); if (supplierId && !supplier) return res.status(400).json({ message: 'Supplier is not active or does not exist' })
  const supplierName = supplier ? String(supplier.name) : legacySupplierName; const supplierState = supplier ? String(supplier.state ?? '') : supplierStateInput; const purchaseId = new ObjectId(); const now = new Date(); const purchaseNumber = `PUR-${now.toISOString().slice(0, 10).replace(/-/g, '')}-${purchaseId.toHexString().slice(-6).toUpperCase()}`; const subtotal = round(quantity * unitPrice); const businessState = typeof settings?.state === 'string' ? settings.state.trim() : ''; const gstType: PurchaseRecord['gstType'] = gstRate <= 0 ? 'none' : businessState && supplierState && businessState.toLowerCase() === supplierState.toLowerCase() ? 'cgst_sgst' : 'igst'; const taxAmount = round(subtotal * gstRate / 100); const cgstAmount = gstType === 'cgst_sgst' ? round(taxAmount / 2) : 0; const sgstAmount = gstType === 'cgst_sgst' ? round(taxAmount - cgstAmount) : 0; const igstAmount = gstType === 'igst' ? taxAmount : 0; const totalAmount = round(subtotal + taxAmount)
  const purchase: PurchaseRecord = { _id: purchaseId, purchaseNumber, ...(supplier ? { supplierId: supplier._id } : {}), supplierName, supplierState, productId: product._id, productName: String(product.name), unit: String(product.unit), quantity, unitPrice, subtotal, gstRate, gstType, cgstAmount, sgstAmount, igstAmount, taxAmount, totalAmount, createdByUserId: req.user!._id, createdAt: now }
  await db.collection<PurchaseRecord>('purchases').insertOne(purchase); await recordAuditEvent({ actorUserId: req.user!._id, actorRole: req.user!.role, action: 'create', entity: 'purchase', entityId: purchaseId.toHexString(), details: { purchaseNumber, supplierId: purchase.supplierId?.toHexString(), supplierName, supplierState, productName: purchase.productName, quantity, subtotal, gstRate, gstType, taxAmount, totalAmount } }); return res.status(201).json({ purchase: sanitizePurchase(purchase) })
})
