import { Router } from 'express'
import { ObjectId } from 'mongodb'
import { getDb } from '../db.js'
import { recordAuditEvent } from '../audit.js'
import { requireAuth, type AuthenticatedRequest } from '../middleware.js'

export interface SaleRecord { _id: ObjectId; invoiceNumber: string; customerId: ObjectId; customerName: string; customerState: string; customerGstNumber: string; productId: ObjectId; productName: string; unit: string; quantity: number; unitPrice: number; subtotal: number; gstRate: number; gstType: 'none' | 'cgst_sgst' | 'igst'; cgstAmount: number; sgstAmount: number; igstAmount: number; taxAmount: number; totalAmount: number; createdByUserId: ObjectId; createdAt: Date }
export const salesRouter = Router(); salesRouter.use(requireAuth)
function sanitizeSale(sale: SaleRecord) { return { id: sale._id.toHexString(), invoiceNumber: sale.invoiceNumber, customerId: sale.customerId.toHexString(), customerName: sale.customerName, customerState: sale.customerState ?? '', customerGstNumber: sale.customerGstNumber ?? '', productId: sale.productId.toHexString(), productName: sale.productName, unit: sale.unit, quantity: sale.quantity, unitPrice: sale.unitPrice, subtotal: sale.subtotal ?? sale.totalAmount, gstRate: sale.gstRate ?? 0, gstType: sale.gstType ?? 'none', cgstAmount: sale.cgstAmount ?? 0, sgstAmount: sale.sgstAmount ?? 0, igstAmount: sale.igstAmount ?? 0, taxAmount: sale.taxAmount ?? 0, totalAmount: sale.totalAmount, createdAt: sale.createdAt } }
salesRouter.get('/', async (_req: AuthenticatedRequest, res) => { const sales = await getDb().collection<SaleRecord>('sales').find({}).sort({ createdAt: -1 }).limit(100).toArray(); return res.json({ sales: sales.map(sanitizeSale) }) })
salesRouter.post('/', async (req: AuthenticatedRequest, res) => {
  const body = req.body as Record<string, unknown> | null; const customerId = typeof body?.customerId === 'string' ? body.customerId : ''; const productId = typeof body?.productId === 'string' ? body.productId : ''; const quantity = typeof body?.quantity === 'number' ? body.quantity : Number(body?.quantity); const unitPrice = typeof body?.unitPrice === 'number' ? body.unitPrice : Number(body?.unitPrice)
  if (!ObjectId.isValid(customerId)) return res.status(400).json({ message: 'Valid customer is required' }); if (!ObjectId.isValid(productId)) return res.status(400).json({ message: 'Valid product is required' }); if (!Number.isFinite(quantity) || quantity <= 0) return res.status(400).json({ message: 'Quantity must be greater than zero' }); if (!Number.isFinite(unitPrice) || unitPrice < 0) return res.status(400).json({ message: 'Price must be a valid non-negative number' })
  const db = getDb(); const customer = await db.collection('customers').findOne({ _id: new ObjectId(customerId), isActive: true }); if (!customer) return res.status(400).json({ message: 'Customer is not active or does not exist' }); const product = await db.collection('products').findOne({ _id: new ObjectId(productId), isActive: true }); if (!product) return res.status(400).json({ message: 'Product is not active or does not exist' })
  const settings = await db.collection('business_settings').findOne({ _id: 'business' }); const gstRateRaw = typeof body?.gstRate === 'number' ? body.gstRate : Number(body?.gstRate ?? settings?.defaultGstRate ?? 0); const gstRate = Number.isFinite(gstRateRaw) ? Math.min(28, Math.max(0, gstRateRaw)) : 0
  const subtotal = Math.round(quantity * unitPrice * 100) / 100; const sameState = Boolean(settings?.state && customer.state && String(settings.state).trim().toLowerCase() === String(customer.state).trim().toLowerCase()); const gstType: SaleRecord['gstType'] = gstRate === 0 ? 'none' : sameState ? 'cgst_sgst' : 'igst'; const taxAmount = Math.round(subtotal * gstRate / 100 * 100) / 100; const cgstAmount = gstType === 'cgst_sgst' ? Math.round(taxAmount / 2 * 100) / 100 : 0; const sgstAmount = gstType === 'cgst_sgst' ? Math.round((taxAmount - cgstAmount) * 100) / 100 : 0; const igstAmount = gstType === 'igst' ? taxAmount : 0; const totalAmount = Math.round((subtotal + taxAmount) * 100) / 100
  const saleId = new ObjectId(); const now = new Date(); const datePart = now.toISOString().slice(0, 10).replace(/-/g, ''); const invoiceNumber = `INV-${datePart}-${saleId.toHexString().slice(-6).toUpperCase()}`
  const sale: SaleRecord = { _id: saleId, invoiceNumber, customerId: customer._id, customerName: String(customer.name), customerState: String(customer.state ?? ''), customerGstNumber: String(customer.gstNumber ?? ''), productId: product._id, productName: String(product.name), unit: String(product.unit), quantity, unitPrice, subtotal, gstRate, gstType, cgstAmount, sgstAmount, igstAmount, taxAmount, totalAmount, createdByUserId: req.user!._id, createdAt: now }
  await db.collection<SaleRecord>('sales').insertOne(sale); await recordAuditEvent({ actorUserId: req.user!._id, actorRole: req.user!.role, action: 'create', entity: 'sale', entityId: saleId.toHexString(), details: { invoiceNumber, customerName: sale.customerName, productName: sale.productName, quantity, subtotal, gstRate, taxAmount, totalAmount } }); return res.status(201).json({ sale: sanitizeSale(sale) })
})
