import { Router } from 'express'
import { ObjectId } from 'mongodb'
import { getDb } from '../db.js'
import { recordAuditEvent } from '../audit.js'
import { requireAuth, type AuthenticatedRequest } from '../middleware.js'

interface SupplierRecord { _id: ObjectId; name: string; phone: string; address: string; gstNumber: string; state: string; isActive: boolean; createdByUserId: ObjectId; createdAt: Date; updatedAt: Date }
export const suppliersRouter = Router(); suppliersRouter.use(requireAuth)
function clean(item: SupplierRecord) { return { id: item._id.toHexString(), name: item.name, phone: item.phone, address: item.address, gstNumber: item.gstNumber, state: item.state, isActive: item.isActive, createdAt: item.createdAt.toISOString(), updatedAt: item.updatedAt.toISOString() } }
function readBody(body: Record<string, unknown> | null) { return { name: typeof body?.name === 'string' ? body.name.trim() : '', phone: typeof body?.phone === 'string' ? body.phone.trim() : '', address: typeof body?.address === 'string' ? body.address.trim() : '', gstNumber: typeof body?.gstNumber === 'string' ? body.gstNumber.trim().toUpperCase() : '', state: typeof body?.state === 'string' ? body.state.trim() : '' } }

suppliersRouter.get('/', async (_req, res) => { const items = await getDb().collection<SupplierRecord>('suppliers').find({}).sort({ isActive: -1, name: 1 }).toArray(); return res.json({ suppliers: items.map(clean) }) })
suppliersRouter.post('/', async (req: AuthenticatedRequest, res) => { const input = readBody(req.body); if (!input.name) return res.status(400).json({ message: 'Supplier name is required.' }); const db = getDb(); const duplicate = await db.collection<SupplierRecord>('suppliers').findOne({ name: input.name }); if (duplicate) return res.status(400).json({ message: 'A supplier with this name already exists.' }); const now = new Date(); const item: SupplierRecord = { _id: new ObjectId(), ...input, isActive: true, createdByUserId: req.user!._id, createdAt: now, updatedAt: now }; await db.collection<SupplierRecord>('suppliers').insertOne(item); await recordAuditEvent({ actorUserId: req.user!._id, actorRole: req.user!.role, action: 'create', entity: 'supplier', entityId: item._id.toHexString(), details: { name: item.name } }); return res.status(201).json({ supplier: clean(item) }) })
suppliersRouter.put('/:id', async (req: AuthenticatedRequest, res) => { const id = String(req.params.id); if (!ObjectId.isValid(id)) return res.status(400).json({ message: 'Valid supplier is required.' }); const input = readBody(req.body); if (!input.name) return res.status(400).json({ message: 'Supplier name is required.' }); const db = getDb(); const objectId = new ObjectId(id); const existing = await db.collection<SupplierRecord>('suppliers').findOne({ _id: objectId }); if (!existing) return res.status(404).json({ message: 'Supplier not found.' }); const duplicate = await db.collection<SupplierRecord>('suppliers').findOne({ _id: { $ne: objectId }, name: input.name }); if (duplicate) return res.status(400).json({ message: 'A supplier with this name already exists.' }); const updatedAt = new Date(); await db.collection<SupplierRecord>('suppliers').updateOne({ _id: objectId }, { $set: { ...input, updatedAt } }); const updated = await db.collection<SupplierRecord>('suppliers').findOne({ _id: objectId }); await recordAuditEvent({ actorUserId: req.user!._id, actorRole: req.user!.role, action: 'update', entity: 'supplier', entityId: id, details: { name: input.name } }); return res.json({ supplier: clean(updated!) }) })
suppliersRouter.put('/:id/status', async (req: AuthenticatedRequest, res) => { const id = String(req.params.id); if (!ObjectId.isValid(id)) return res.status(400).json({ message: 'Valid supplier is required.' }); const isActive = Boolean(req.body?.isActive); const db = getDb(); const objectId = new ObjectId(id); const existing = await db.collection<SupplierRecord>('suppliers').findOne({ _id: objectId }); if (!existing) return res.status(404).json({ message: 'Supplier not found.' }); await db.collection<SupplierRecord>('suppliers').updateOne({ _id: objectId }, { $set: { isActive, updatedAt: new Date() } }); const updated = await db.collection<SupplierRecord>('suppliers').findOne({ _id: objectId }); await recordAuditEvent({ actorUserId: req.user!._id, actorRole: req.user!.role, action: 'update', entity: 'supplier', entityId: id, details: { isActive } }); return res.json({ supplier: clean(updated!) }) })
