import { useEffect, useMemo, useState } from 'react'
import { Button } from '../components/Button'
import { listCustomers, type Customer } from '../lib/customers'
import { getCustomerAccount, getSupplierAccount, type AccountStatement } from '../lib/accounts'
import { listPurchases, type Purchase } from '../lib/purchases'

type AccountTab = 'customer' | 'supplier'
const money = (value: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 2 }).format(value)
const date = (value: string) => value ? new Date(value).toLocaleDateString('en-IN') : '—'
const isoDate = (value: Date) => value.toISOString().slice(0, 10)

export function Accounts() {
  const [tab, setTab] = useState<AccountTab>('customer'); const [customers, setCustomers] = useState<Customer[]>([]); const [purchases, setPurchases] = useState<Purchase[]>([]); const [selectedCustomer, setSelectedCustomer] = useState(''); const [selectedSupplier, setSelectedSupplier] = useState(''); const [statement, setStatement] = useState<AccountStatement | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [fromDate, setFromDate] = useState(''); const [toDate, setToDate] = useState('')
  const suppliers = useMemo(() => [...new Map(purchases.map((purchase) => [purchase.supplierName.trim().toLowerCase(), purchase.supplierName.trim()])).values()].filter(Boolean).sort((a, b) => a.localeCompare(b)), [purchases])
  const filteredEntries = useMemo(() => { if (!statement) return []; return statement.statement.filter((entry) => (!fromDate || entry.date.slice(0, 10) >= fromDate) && (!toDate || entry.date.slice(0, 10) <= toDate)) }, [statement, fromDate, toDate])
  const filteredOutstanding = useMemo(() => { if (!statement) return 0; if (!fromDate && !toDate) return statement.outstanding; if (!filteredEntries.length) return 0; return filteredEntries[filteredEntries.length - 1].balance }, [statement, filteredEntries, fromDate, toDate])
  useEffect(() => { Promise.all([listCustomers(), listPurchases()]).then(([customerList, purchaseList]) => { setCustomers(customerList); setPurchases(purchaseList); if (customerList[0]) setSelectedCustomer(customerList[0].id); if (purchaseList[0]) setSelectedSupplier(purchaseList[0].supplierName) }).catch((errorValue) => setError(errorValue instanceof Error ? errorValue.message : 'Unable to load accounts.')).finally(() => setLoading(false)) }, [])
  useEffect(() => { if (loading) return; setStatement(null); if (tab === 'customer' && selectedCustomer) void loadCustomer(selectedCustomer); if (tab === 'supplier' && selectedSupplier) void loadSupplier(selectedSupplier) }, [tab, selectedCustomer, selectedSupplier, loading])
  async function loadCustomer(id: string) { setBusy(true); setError(''); try { setStatement(await getCustomerAccount(id)) } catch (errorValue) { setError(errorValue instanceof Error ? errorValue.message : 'Unable to load customer account.') } finally { setBusy(false) } }
  async function loadSupplier(name: string) { setBusy(true); setError(''); try { setStatement(await getSupplierAccount(name)) } catch (errorValue) { setError(errorValue instanceof Error ? errorValue.message : 'Unable to load supplier account.') } finally { setBusy(false) } }
  function resetDates() { setFromDate(''); setToDate('') }
  function printStatement() { window.print() }
  async function shareStatement() { if (!statement) return; const title = `${tab === 'customer' ? 'Customer' : 'Supplier'} Statement - ${statement.account.name}`; const lines = filteredEntries.slice().reverse().map((entry) => `${date(entry.date)} | ${entry.description} | ${money(entry.debit || entry.credit)} | Balance ${money(entry.balance)}`); const text = `${title}\n${fromDate || toDate ? `Period: ${fromDate || 'Start'} to ${toDate || 'Today'}\n` : ''}\n${lines.join('\n')}\n\nOutstanding: ${money(filteredOutstanding)}`; try { if (navigator.share) await navigator.share({ title, text }); else await navigator.clipboard.writeText(text) } catch { /* User cancelled native share. */ } }
  return <div className="accounts-page">
    <section className="page-heading"><p className="eyebrow">Accounts</p><h2>Customer & Supplier Accounts</h2><p>See every sale or purchase and the payments that settle it.</p></section>
    <section className="form-card no-print"><div className="form-actions"><Button variant={tab === 'customer' ? 'primary' : 'secondary'} type="button" onClick={() => setTab('customer')}>Customer accounts</Button><Button variant={tab === 'supplier' ? 'primary' : 'secondary'} type="button" onClick={() => setTab('supplier')}>Supplier accounts</Button></div>{tab === 'customer' ? <label>Customer<select value={selectedCustomer} onChange={(event) => setSelectedCustomer(event.target.value)}><option value="">Select customer</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.name}{customer.isActive ? '' : ' (Inactive)'}</option>)}</select></label> : <label>Supplier<select value={selectedSupplier} onChange={(event) => setSelectedSupplier(event.target.value)}><option value="">Select supplier</option>{suppliers.map((supplier) => <option key={supplier} value={supplier}>{supplier}</option>)}</select></label>}<div className="date-filter"><label>From<input type="date" value={fromDate} max={toDate || isoDate(new Date())} onChange={(event) => setFromDate(event.target.value)} /></label><label>To<input type="date" value={toDate} min={fromDate} max={isoDate(new Date())} onChange={(event) => setToDate(event.target.value)} /></label><Button variant="secondary" type="button" onClick={resetDates}>All dates</Button></div></section>
    {error && <p className="error-text" role="alert">{error}</p>}{loading || busy ? <p className="field-hint">Loading account…</p> : !statement ? <section className="empty-state"><h3>Select an account</h3><p>Choose a customer or supplier to see its statement.</p></section> : <><section className="summary-grid"><SummaryCard label={tab === 'customer' ? 'Customer' : 'Supplier'} value={statement.account.name}/><SummaryCard label={tab === 'customer' ? 'Customer outstanding' : 'Supplier payable'} value={money(filteredOutstanding)}/><SummaryCard label="Entries" value={String(filteredEntries.length)}/></section><section className="user-list"><div className="list-heading"><div><h3>Statement</h3><span className="field-hint">{fromDate || toDate ? `${fromDate || 'Start'} to ${toDate || 'Today'}` : 'All dates'} · Latest balance shown on each row</span></div><div className="form-actions no-print"><Button variant="secondary" type="button" onClick={printStatement}>Print / PDF</Button><Button variant="secondary" type="button" onClick={() => void shareStatement()}>Share</Button></div></div>{filteredEntries.length === 0 ? <p className="field-hint">No transactions in this date range.</p> : filteredEntries.slice().reverse().map((entry) => <article className="user-row" key={entry.id}><div><strong>{entry.description}</strong><span>{date(entry.date)} · {entry.number}</span></div><div><strong>{tab === 'customer' ? entry.debit ? money(entry.debit) : money(entry.credit) : entry.credit ? money(entry.credit) : money(entry.debit)}</strong><span>{tab === 'customer' ? entry.debit ? 'Sale' : 'Receipt' : entry.credit ? 'Purchase' : 'Payment'} · Balance {money(entry.balance)}</span></div></article>)}</section></>}
  </div>
}
function SummaryCard({ label, value }: { label: string; value: string }) { return <article className="summary-card"><p>{label}</p><strong>{value}</strong></article> }
