import { browserSupportsPasskeys } from '@simplewebauthn/browser'
import { useEffect, useState, type FormEvent } from 'react'
import { Button } from '../components/Button'
import { Icon } from '../components/Icon'
import { registerPasskey, signIn, signInWithPasskey, signOut } from '../lib/auth/auth'
import { useAuth } from '../lib/auth/AuthProvider'
import { Home } from './Home'
import { Sales } from './Sales'
import { Purchases } from './Purchases'
import { Inventory } from './Inventory'
import { People } from './People'
import { Accounts } from './Accounts'
import { Operations } from './Operations'
import { Payments } from './Payments'
import { Documents } from './Documents'
import { History } from './History'
import { ReportsHub } from './ReportsHub'
import { Users } from './Users'
import { Settings } from './Settings'
import './navigation.css'

type Section='home'|'sales'|'purchases'|'inventory'|'people'|'accounts'|'operations'|'payments'|'documents'|'history'|'reports'|'users'|'settings'
const titles:Record<Section,string>={home:'Home',sales:'Sales',purchases:'Purchases',inventory:'Inventory',people:'People',accounts:'Accounts',operations:'Expenses & bills',payments:'Payments',documents:'Documents',history:'History',reports:'Reports',users:'Users',settings:'Settings'}
const more:Array<[Section,string]>=[['purchases','Purchases'],['people','People'],['operations','Expenses & bills'],['payments','Payments'],['reports','Reports'],['documents','Documents'],['history','History']]
export function App(){const{loading,configured,session,user}=useAuth();if(!configured)return <Notice title="Start the API">The MERN API is not reachable yet. Start the Node server.</Notice>;if(loading)return <Notice>Loading your account…</Notice>;if(!session)return <SignIn/>;if(!user?.profile?.isActive)return <Notice title="Account unavailable">Contact the owner. This account is currently inactive.</Notice>;return <Main/>}
function Main(){const{user}=useAuth();const[section,setSection]=useState<Section>('home');const[moreOpen,setMoreOpen]=useState(false);const[profileOpen,setProfileOpen]=useState(false);const owner=user?.profile?.role==='owner';const go=(s:Section)=>{setSection(s);setMoreOpen(false);setProfileOpen(false);window.scrollTo({top:0,behavior:'smooth'})};return <div className="app-shell"><header className="topbar"><div className="topbar-title"><p className="eyebrow">Paul Bricks & Blocks</p><h1>{titles[section]}</h1></div><div className="topbar-account"><button className="avatar-button" type="button" aria-label="Open account menu" onClick={()=>setProfileOpen(v=>!v)}><Icon name="user" size={21}/></button>{profileOpen&&<div className="profile-menu"><strong>{user?.email}</strong><span>{owner?'Owner':'Partner'}</span><PasskeySetup/>{owner&&<><Button variant="ghost" onClick={()=>go('users')}>Users</Button><Button variant="ghost" onClick={()=>go('settings')}>Settings</Button></>}<Button variant="ghost" onClick={()=>void signOut()}>Sign out</Button></div>}</div></header><main className="page-content"><Content section={section} go={go}/></main><nav className="bottom-nav" aria-label="Main navigation"><Nav id="home" label="Home" icon="home" s={section} go={go}/><Nav id="sales" label="Sales" icon="sales" s={section} go={go}/><Nav id="inventory" label="Inventory" icon="stock" s={section} go={go}/><Nav id="accounts" label="Accounts" icon="accounts" s={section} go={go}/><Button variant={moreOpen||more.some(([id])=>id===section)?'active':'nav'} onClick={()=>setMoreOpen(v=>!v)}><span className="nav-icon"><Icon name="more" size={20}/></span><span>More</span></Button></nav>{moreOpen&&<div className="more-sheet-backdrop" onClick={()=>setMoreOpen(false)}><section className="more-sheet" role="dialog" aria-modal="true" onClick={e=>e.stopPropagation()}><div className="sheet-handle"/><div className="more-sheet-heading"><div><p className="eyebrow">More</p><h2>Business tools</h2></div><Button variant="icon" onClick={()=>setMoreOpen(false)} aria-label="Close"><Icon name="close" size={19}/></Button></div><div className="more-section-list">{more.map(([id,label])=><button key={id} type="button" className={`more-section-button ${section===id?'current':''}`.trim()} onClick={()=>go(id)}><span>{label}</span><Icon name="chevron" size={17}/></button>)}</div></section></div>}</div>}
function Nav({id,label,icon,s,go}:{id:Section;label:string;icon:'home'|'sales'|'stock'|'user'|'accounts';s:Section;go:(s:Section)=>void}){return <Button variant={s===id?'active':'nav'} onClick={()=>go(id)}><span className="nav-icon"><Icon name={icon} size={20}/></span><span>{label}</span></Button>}
function Content({section,go}:{section:Section;go:(s:Section)=>void}){switch(section){case'home':return <Home go={go}/>;case'sales':return <Sales/>;case'purchases':return <Purchases/>;case'inventory':return <Inventory/>;case'people':return <People/>;case'accounts':return <Accounts/>;case'operations':return <Operations/>;case'payments':return <Payments/>;case'documents':return <Documents/>;case'history':return <History/>;case'reports':return <ReportsHub/>;case'users':return <Users/>;case'settings':return <Settings/>}}
function PasskeySetup(){const[available,setAvailable]=useState<boolean|null>(null);const[busy,setBusy]=useState(false);useEffect(()=>{void browserSupportsPasskeys().then(setAvailable).catch(()=>setAvailable(false))},[]);if(available===false)return null;async function setup(){setBusy(true);try{await registerPasskey()}finally{setBusy(false)}}return <Button variant="ghost" type="button" disabled={busy} onClick={()=>void setup()}>{busy?'Setting up…':'Set up passkey'}</Button>}
function SignIn(){const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[pk,setPk]=useState<boolean|null>(null);useEffect(()=>{void browserSupportsPasskeys().then(setPk).catch(()=>setPk(false))},[]);async function passkey(){setBusy(true);setError('');try{await signInWithPasskey()}catch(e){setError(e instanceof Error?e.message:'Unable to sign in with passkey.')}finally{setBusy(false)}}async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{await signIn(email.trim(),password)}catch(v){setError(v instanceof Error?v.message:'Unable to sign in.')}finally{setBusy(false)}}return <main className="auth-screen"><section className="auth-card"><p className="eyebrow">Paul Bricks & Blocks</p><h1>Sign in</h1>{pk!==false&&<Button variant="primary" type="button" disabled={busy} onClick={()=>void passkey()}>Sign in with passkey</Button>}<p className="field-hint">Or use your email and password.</p><form onSubmit={submit} className="auth-form"><label>Email<input type="email" autoComplete="username webauthn" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<p className="error-text" role="alert">{error}</p>}<Button variant="secondary" type="submit" disabled={busy}>Use password</Button></form></section></main>}
function Notice({title='Loading',children}:{title?:string;children:string}){return <main className="auth-screen"><section className="auth-card"><p className="eyebrow">Paul Bricks & Blocks</p><h1>{title}</h1><p>{children}</p></section></main>}
