import { useEffect, useState, type FormEvent } from 'react'
import { Button } from '../components/Button'
import { FormSheet } from '../components/FormSheet'
import { createCustomer, listCustomers, updateCustomer, type Customer } from '../lib/customers'

const emptyForm = { name: '', phone: '', address: '', state: '', gstNumber: '' }
type CustomerForm = typeof emptyForm

export function Customers() {
  const [customers, setCustomers] = useState<Customer[]>([]); const [form, setForm] = useState<CustomerForm>(emptyForm); const [editingId, setEditingId] = useState<string | null>(null); const [formOpen, setFormOpen] = useState(false); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('')
  async function loadCustomers() { setLoading(true); setError(''); try { setCustomers(await listCustomers()) } catch (errorValue) { setError(errorValue instanceof Error ? errorValue.message : 'Unable to load customers.') } finally { setLoading(false) } }
  useEffect(() => { void loadCustomers() }, [])
  function resetForm() { setForm(emptyForm); setEditingId(null); setFormOpen(false); setError('') }
  function openNew() { setForm(emptyForm); setEditingId(null); setError(''); setSuccess(''); setFormOpen(true) }
  function startEditing(customer: Customer) { setEditingId(customer.id); setForm({ name: customer.name, phone: customer.phone, address: customer.address, state: customer.state, gstNumber: customer.gstNumber }); setSuccess(''); setError(''); setFormOpen(true) }
  async function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); setSuccess(''); setBusy(true); try { if (editingId) { await updateCustomer(editingId, form); setSuccess('Customer details updated.') } else { await createCustomer(form); setSuccess('Customer added.') }; resetForm(); await loadCustomers() } catch (errorValue) { setError(errorValue instanceof Error ? errorValue.message : 'Unable to save customer.') } finally { setBusy(false) } }
  async function toggleCustomer(customer: Customer) { setError(''); setSuccess(''); setBusy(true); try { await updateCustomer(customer.id, { name: customer.name, phone: customer.phone, address: customer.address, state: customer.state, gstNumber: customer.gstNumber, isActive: !customer.isActive }); setSuccess(customer.isActive ? 'Customer marked inactive.' : 'Customer marked active.'); await loadCustomers() } catch (errorValue) { setError(errorValue instanceof Error ? errorValue.message : 'Unable to update customer.') } finally { setBusy(false) } }
  return <div className="customers-page"><section className="page-heading"><div><p className="eyebrow">Business</p><h2>Customers</h2><p>Keep your customer list ready for sales, GST and payments.</p></div><Button variant="primary" onClick={openNew}>+ Add customer</Button></section>{error && <p className="error-text" role="alert">{error}</p>}{success && <p className="success-text" role="status">{success}</p>}<section className="user-list customer-list"><div className="list-heading"><div><h3>Customer list</h3><span className="field-hint">{customers.length} total</span></div><Button variant="secondary" onClick={() => void loadCustomers()} disabled={loading}>Refresh</Button></div>{loading ? <p className="field-hint">Loading customers…</p> : customers.length === 0 ? <div className="empty-inline"><p className="field-hint">No customers yet.</p><Button variant="primary" onClick={openNew}>Add your first customer</Button></div> : customers.map((customer) => <article className="user-row customer-row" key={customer.id}><div><strong>{customer.name}</strong><span>{customer.phone || 'No phone number'}{customer.gstNumber ? ` · GST ${customer.gstNumber}` : ''}</span>{customer.state && <span>{customer.state}</span>}{customer.address && <span>{customer.address}</span>}</div><div className="row-actions"><span className="status-badge">{customer.isActive ? 'Active' : 'Inactive'}</span><Button variant="secondary" type="button" onClick={() => startEditing(customer)} disabled={busy}>Edit</Button><Button variant="secondary" type="button" onClick={() => void toggleCustomer(customer)} disabled={busy}>{customer.isActive ? 'Disable' : 'Enable'}</Button></div></article>)}</section>{formOpen && <FormSheet title={editingId ? 'Edit customer' : 'Add customer'} onClose={() => !busy && resetForm()}><form className="customer-form" onSubmit={handleSubmit}><label>Customer name<input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required autoFocus /></label><label>Phone number<input type="tel" value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} /></label><label>Address<textarea rows={3} value={form.address} onChange={(event) => setForm({ ...form, address: event.target.value })} /></label><label>State<span className="field-hint"> Used for GST place of supply</span><input value={form.state} onChange={(event) => setForm({ ...form, state: event.target.value })} placeholder="Example: Karnataka" /></label><label>GST number<span className="field-hint"> Optional</span><input value={form.gstNumber} onChange={(event) => setForm({ ...form, gstNumber: event.target.value.toUpperCase() })} /></label>{error && <p className="error-text" role="alert">{error}</p>}<div className="form-actions"><Button variant="primary" type="submit" disabled={busy}>{busy ? 'Saving…' : editingId ? 'Save changes' : 'Add customer'}</Button></div></form></FormSheet>}</div>
}
