import { useEffect, useMemo, useState } from 'react'
import { Button } from '../components/Button'
import { FormSheet } from '../components/FormSheet'
import { deleteAttachment, listAttachments, openAttachment, uploadAttachment, type Attachment, type AttachmentEntityType } from '../lib/attachments'
import { listCustomers, type Customer } from '../lib/customers'
import { listSuppliers, type Supplier } from '../lib/suppliers'
import { listProducts, type Product } from '../lib/products'
import { listSales, type Sale } from '../lib/sales'
import { listPurchases, type Purchase } from '../lib/purchases'
import { listExpenses, type Expense } from '../lib/expenses'
import { listBills, type Bill } from '../lib/bills'
type RecordItem = { id: string; label: string; detail?: string }
const typeLabels: Array<{ id: AttachmentEntityType; label: string }> = [{ id: 'customer', label: 'Customer' }, { id: 'supplier', label: 'Supplier' }, { id: 'product', label: 'Product' }, { id: 'sale', label: 'Sale / Invoice' }, { id: 'purchase', label: 'Purchase' }, { id: 'expense', label: 'Expense' }, { id: 'bill', label: 'Bill' }]
const emptyRecords: Record<AttachmentEntityType, RecordItem[]> = { customer: [], supplier: [], product: [], sale: [], purchase: [], expense: [], bill: [] }
const sizeLabel = (bytes: number) => bytes < 1024 * 1024 ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`
export function Documents() {
  const [records, setRecords] = useState(emptyRecords); const [entityType, setEntityType] = useState<AttachmentEntityType>('customer'); const [entityId, setEntityId] = useState(''); const [attachments, setAttachments] = useState<Attachment[]>([]); const [formOpen, setFormOpen] = useState(false); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('')
  async function loadRecords() { setLoading(true); setError(''); try { const [customers, suppliers, products, sales, purchases, expenses, bills] = await Promise.all([listCustomers(), listSuppliers(), listProducts(), listSales(), listPurchases(), listExpenses(), listBills()]); setRecords({ customer: customers.map((x: Customer) => ({ id: x.id, label: x.name, detail: x.phone })), supplier: suppliers.map((x: Supplier) => ({ id: x.id, label: x.name, detail: x.state })), product: products.map((x: Product) => ({ id: x.id, label: x.name, detail: `${x.unit} · ₹${x.sellingPrice.toFixed(2)}` })), sale: sales.map((x: Sale) => ({ id: x.id, label: x.invoiceNumber, detail: `${x.customerName} · ₹${x.totalAmount.toFixed(2)}` })), purchase: purchases.map((x: Purchase) => ({ id: x.id, label: x.purchaseNumber, detail: `${x.supplierName} · ₹${x.totalAmount.toFixed(2)}` })), expense: expenses.map((x: Expense) => ({ id: x.id, label: x.expenseNumber, detail: `${x.category} · ₹${x.amount.toFixed(2)}` })), bill: bills.map((x: Bill) => ({ id: x.id, label: x.billNumber, detail: `${x.title} · ₹${x.amount.toFixed(2)}` })) }) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load records.') } finally { setLoading(false) } }
  async function loadAttachments(id = entityId, type = entityType) { if (!id) { setAttachments([]); return }; try { setAttachments(await listAttachments(type, id)) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load documents.') } }
  useEffect(() => { void loadRecords() }, [])
  useEffect(() => { const first = records[entityType][0]?.id ?? ''; setEntityId(first); void loadAttachments(first, entityType) }, [entityType, records])
  useEffect(() => { if (entityId) void loadAttachments() }, [entityId])
  const selectedLabel = useMemo(() => records[entityType].find(item => item.id === entityId)?.label ?? '', [records, entityType, entityId])
  async function handleFiles(files: FileList | null) { if (!files?.length || !entityId) return; setBusy(true); setError(''); setSuccess(''); try { for (const file of Array.from(files)) await uploadAttachment(entityType, entityId, file); await loadAttachments(); setSuccess(files.length === 1 ? 'Document attached.' : `${files.length} documents attached.`); setFormOpen(false) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to attach document.') } finally { setBusy(false) } }
  async function remove(id: string) { if (!window.confirm('Delete this document?')) return; setBusy(true); setError(''); try { await deleteAttachment(id); await loadAttachments(); setSuccess('Document deleted.') } catch (e) { setError(e instanceof Error ? e.message : 'Unable to delete document.') } finally { setBusy(false) } }
  return <div className="documents-page"><section className="page-heading"><div><p className="eyebrow">Business</p><h2>Documents</h2><p>Choose a business record to see its attached files.</p></div><Button variant="primary" onClick={() => { setError(''); setFormOpen(true) }}>+ Attach document</Button></section>{error && <p className="error-text" role="alert">{error}</p>}{success && <p className="success-text" role="status">{success}</p>}<section className="form-card"><div className="list-heading"><div><h3>Record documents</h3><span className="field-hint">{selectedLabel || 'Choose a record'}</span></div><Button variant="secondary" type="button" onClick={() => void loadAttachments()} disabled={busy || !entityId}>Refresh</Button></div><div className="customer-form"><label>Record type<select value={entityType} onChange={e => setEntityType(e.target.value as AttachmentEntityType)}>{typeLabels.map(item => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label>Choose record<select value={entityId} onChange={e => setEntityId(e.target.value)} disabled={loading || records[entityType].length === 0}><option value="">Choose a record</option>{records[entityType].map(item => <option key={item.id} value={item.id}>{item.label}{item.detail ? ` — ${item.detail}` : ''}</option>)}</select></label></div></section><section className="user-list"><div className="list-heading"><h3>Attached files</h3></div>{!entityId ? <p className="field-hint">Choose a record to see its documents.</p> : attachments.length === 0 ? <div className="empty-inline"><p className="field-hint">No documents attached to this record yet.</p><Button variant="primary" onClick={() => setFormOpen(true)}>Attach a file</Button></div> : attachments.map(file => <article className="user-row" key={file.id}><div><strong>{file.fileName}</strong><span>{sizeLabel(file.size)} · {new Date(file.uploadedAt).toLocaleString('en-IN')}</span></div><div className="row-actions"><Button variant="secondary" type="button" onClick={() => void openAttachment(file.id, file.fileName)}>Open</Button><Button variant="secondary" type="button" onClick={() => void remove(file.id)} disabled={busy}>Delete</Button></div></article>)}</section>{formOpen && <FormSheet title="Attach document" onClose={() => !busy && setFormOpen(false)}><div className="customer-form"><p className="field-hint">Attach files to <strong>{selectedLabel || 'the selected record'}</strong>. Maximum 5 MB per file.</p><label className="file-picker">Add file<input type="file" accept="image/*,.pdf,.txt,.doc,.docx,.xls,.xlsx" multiple disabled={busy || !entityId} onChange={e => { void handleFiles(e.target.files); e.currentTarget.value = '' }} /><span className="field-hint">PDF, image or office document.</span></label></div></FormSheet>}</div>
}
