import { useEffect, useState, type FormEvent } from 'react'
import { Button } from '../components/Button'
import { FormSheet } from '../components/FormSheet'
import { createExpense, listExpenses, type Expense } from '../lib/expenses'
const money = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 2 }); const categories = ['Electricity', 'Transport', 'Diesel', 'Repairs', 'Office', 'Rent', 'Other']; function today() { return new Date().toISOString().slice(0, 10) }
export function Expenses() { const [expenses, setExpenses] = useState<Expense[]>([]); const [category, setCategory] = useState(''); const [description, setDescription] = useState(''); const [amount, setAmount] = useState(''); const [expenseDate, setExpenseDate] = useState(today); const [formOpen, setFormOpen] = useState(false); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('')
  async function load() { setLoading(true); setError(''); try { setExpenses(await listExpenses()) } catch (errorValue) { setError(errorValue instanceof Error ? errorValue.message : 'Unable to load expenses.') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  function openNew() { setCategory(''); setDescription(''); setAmount(''); setExpenseDate(today()); setError(''); setSuccess(''); setFormOpen(true) }
  async function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); setSuccess(''); setBusy(true); try { const expense = await createExpense({ category: category.trim(), description: description.trim(), amount: Number(amount), expenseDate }); setExpenses((current) => [expense, ...current]); setSuccess(`Expense saved as ${expense.expenseNumber}.`); setFormOpen(false); setCategory(''); setDescription(''); setAmount(''); setExpenseDate(today()) } catch (errorValue) { setError(errorValue instanceof Error ? errorValue.message : 'Unable to save expense.') } finally { setBusy(false) } }
  return <div className="expenses-page"><section className="page-heading"><div><p className="eyebrow">Money</p><h2>Expenses</h2><p>Your business expense records.</p></div><Button variant="primary" onClick={openNew}>+ Add expense</Button></section>{error && <p className="error-text" role="alert">{error}</p>}{success && <p className="success-text" role="status">{success}</p>}<section className="user-list"><div className="list-heading"><div><h3>Recent expenses</h3><span className="field-hint">{expenses.length} records</span></div><Button variant="secondary" onClick={() => void load()} disabled={loading}>Refresh</Button></div>{loading ? <p>Loading expenses…</p> : expenses.length === 0 ? <div className="empty-inline"><p>No expenses yet.</p><Button variant="primary" onClick={openNew}>Add your first expense</Button></div> : expenses.map((expense) => <article className="user-row expense-row" key={expense.id}><div><strong>{expense.category}</strong><span>{expense.description || 'No description'} · {expense.expenseDate} · {expense.expenseNumber}</span></div><div className="row-actions"><strong>{money.format(expense.amount)}</strong></div></article>)}</section>{formOpen && <FormSheet title="New expense" onClose={() => !busy && setFormOpen(false)}><form className="customer-form" onSubmit={handleSubmit}><label>Category<select value={category} onChange={(event) => setCategory(event.target.value)} required><option value="">Choose category</option>{categories.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label>Description <span className="field-hint">(optional)</span><input value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Example: Diesel for delivery" /></label><label>Amount<input type="number" min="0.01" step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="0.00" required /></label><label>Date<input type="date" value={expenseDate} onChange={(event) => setExpenseDate(event.target.value)} required /></label>{error && <p className="error-text" role="alert">{error}</p>}<div className="form-actions"><Button variant="primary" type="submit" disabled={busy || loading}>{busy ? 'Saving…' : 'Save expense'}</Button></div></form></FormSheet>}</div>
}
