import { useEffect, useState } from 'react'
import { Button } from '../components/Button'
import { getReportSummary, type ReportSummary } from '../lib/reports'
const money = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 2 })
function today() { return new Date().toISOString().slice(0, 10) }
function daysAgo(days: number) { const date = new Date(); date.setDate(date.getDate() - days); return date.toISOString().slice(0, 10) }
export function Reports() {
  const [from, setFrom] = useState(today()); const [to, setTo] = useState(today()); const [report, setReport] = useState<ReportSummary | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  async function load(nextFrom = from, nextTo = to) { setError(''); setBusy(true); try { setReport(await getReportSummary(nextFrom, nextTo)) } catch (errorValue) { setError(errorValue instanceof Error ? errorValue.message : 'Unable to load report.') } finally { setBusy(false); setLoading(false) } }
  useEffect(() => { void load() }, [])
  function applyRange(nextFrom: string, nextTo: string) { setFrom(nextFrom); setTo(nextTo); void load(nextFrom, nextTo) }
  return <div className="reports-page">
    <section className="page-heading"><p className="eyebrow">Accounts</p><h2>Reports</h2><p>See sales, stock cost and profit for any date range.</p></section>
    <section className="form-card report-filter-card"><h3>Date range</h3><div className="report-presets"><Button variant="secondary" type="button" onClick={() => applyRange(today(), today())}>Today</Button><Button variant="secondary" type="button" onClick={() => applyRange(daysAgo(6), today())}>7 days</Button><Button variant="secondary" type="button" onClick={() => { const d = new Date(); d.setDate(1); applyRange(d.toISOString().slice(0, 10), today()) }}>This month</Button></div><div className="report-date-grid"><label>From<input type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label>To<input type="date" value={to} onChange={(event) => setTo(event.target.value)} /></label></div><Button variant="primary" type="button" onClick={() => void load()} disabled={busy || !from || !to}>{busy ? 'Loading…' : 'Show report'}</Button></section>
    {error && <p className="error-text" role="alert">{error}</p>}
    {loading ? <section className="empty-state"><p>Loading report…</p></section> : report && <>
      <section className="summary-grid report-summary-grid"><article className="summary-card"><p>Sales</p><strong>{money.format(report.sales.subtotal)}</strong><span>before GST</span></article><article className="summary-card"><p>COGS</p><strong>{money.format(report.cogs)}</strong><span>cost of goods sold</span></article><article className="summary-card"><p>Gross Profit</p><strong>{money.format(report.grossProfit)}</strong><span>sales minus COGS</span></article><article className="summary-card"><p>Operating Profit</p><strong>{money.format(report.operatingProfit)}</strong><span>after expenses + labour</span></article></section>
      <section className="user-list report-section"><h3>Profit summary</h3><div className="report-line"><span>Sales before GST</span><strong>{money.format(report.sales.subtotal)}</strong></div><div className="report-line"><span>Cost of goods sold</span><strong>{money.format(report.cogs)}</strong></div><div className="report-line"><span>Gross profit</span><strong>{money.format(report.grossProfit)}</strong></div><div className="report-line"><span>Expenses + Labour</span><strong>{money.format(report.expensesAndLabour)}</strong></div><div className="report-line report-total"><span>Operating profit</span><strong>{money.format(report.operatingProfit)}</strong></div><div className="report-line"><span>Closing stock value</span><strong>{money.format(report.closingStockValue)}</strong></div></section>
      <section className="user-list report-section"><h3>Money & GST</h3><div className="report-line"><span>Sales total including GST</span><strong>{money.format(report.sales.total)}</strong></div><div className="report-line"><span>Purchases including GST</span><strong>{money.format(report.purchases.total)}</strong></div><div className="report-line"><span>GST collected from sales</span><strong>{money.format(report.sales.gst)}</strong></div><div className="report-line"><span>Purchase input GST</span><strong>{money.format(report.purchases.inputGst)}</strong></div><div className="report-line"><span>Output GST − input GST</span><strong>{money.format(report.gstDifference)}</strong></div><div className="report-line"><span>Unpaid bills in period</span><strong>{money.format(report.unpaidBills.total)} ({report.unpaidBills.count})</strong></div></section>
      <section className="empty-state report-note"><p className="eyebrow">Accounting notes</p><p>{report.stockNote}</p><p>{report.gstNote}</p></section>
    </>}
  </div>
}
