import { useEffect, useState, type FormEvent } from 'react'
import { Button } from '../components/Button'
import { FormSheet } from '../components/FormSheet'
import { createSupplier, listSuppliers, setSupplierStatus, updateSupplier, type Supplier } from '../lib/suppliers'

const empty = { name: '', phone: '', address: '', gstNumber: '', state: '' }
export function Suppliers() {
  const [suppliers, setSuppliers] = useState<Supplier[]>([]); const [form, setForm] = useState(empty); const [editingId, setEditingId] = useState<string | null>(null); const [formOpen, setFormOpen] = useState(false); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('')
  async function load() { setLoading(true); try { setSuppliers(await listSuppliers()) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load suppliers.') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  function openNew() { setEditingId(null); setForm(empty); setError(''); setSuccess(''); setFormOpen(true) }
  function edit(item: Supplier) { setEditingId(item.id); setForm({ name: item.name, phone: item.phone, address: item.address, gstNumber: item.gstNumber, state: item.state }); setError(''); setSuccess(''); setFormOpen(true) }
  function cancel() { setEditingId(null); setForm(empty); setFormOpen(false); setError('') }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); setSuccess(''); try { if (editingId) { await updateSupplier(editingId, form); setSuccess('Supplier updated.') } else { await createSupplier(form); setSuccess('Supplier added.') } cancel(); await load() } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save supplier.') } finally { setBusy(false) } }
  async function toggle(item: Supplier) { setError(''); try { await setSupplierStatus(item.id, !item.isActive); await load() } catch (e) { setError(e instanceof Error ? e.message : 'Unable to update supplier.') } }
  return <div className="suppliers-page"><section className="page-heading"><div><p className="eyebrow">Business</p><h2>Suppliers</h2><p>Keep supplier details in one simple place for purchases, payments and accounts.</p></div><Button variant="primary" onClick={openNew}>+ Add supplier</Button></section>{error && <p className="error-text" role="alert">{error}</p>}{success && <p className="success-text" role="status">{success}</p>}<section className="user-list"><div className="list-heading"><div><h3>Supplier list</h3><span className="field-hint">{suppliers.length} total</span></div><Button variant="secondary" type="button" onClick={() => void load()} disabled={loading}>Refresh</Button></div>{loading ? <p className="field-hint">Loading suppliers…</p> : suppliers.length === 0 ? <div className="empty-inline"><p className="field-hint">No suppliers yet.</p><Button variant="primary" onClick={openNew}>Add your first supplier</Button></div> : suppliers.map(item => <article className="user-row customer-row" key={item.id}><div><strong>{item.name}</strong><span>{item.phone || 'No phone'} · {item.state || 'No state'}</span><span>{item.gstNumber ? `GSTIN: ${item.gstNumber}` : 'No GSTIN'}{item.address ? ` · ${item.address}` : ''}</span></div><div className="row-actions"><span className="status-badge">{item.isActive ? 'Active' : 'Inactive'}</span><Button variant="secondary" type="button" onClick={() => edit(item)}>Edit</Button><Button variant="secondary" type="button" onClick={() => void toggle(item)}>{item.isActive ? 'Disable' : 'Enable'}</Button></div></article>)}</section>{formOpen && <FormSheet title={editingId ? 'Edit supplier' : 'Add supplier'} onClose={() => !busy && cancel()}><form className="customer-form" onSubmit={submit}><label>Supplier name<input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="Example: ABC Bricks Supplier" required autoFocus /></label><label>Phone<input value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} placeholder="Phone number" /></label><label>Address<textarea rows={2} value={form.address} onChange={e => setForm({ ...form, address: e.target.value })} placeholder="Supplier address" /></label><label>GSTIN<input value={form.gstNumber} onChange={e => setForm({ ...form, gstNumber: e.target.value.toUpperCase() })} placeholder="Optional GST number" /></label><label>State<input value={form.state} onChange={e => setForm({ ...form, state: e.target.value })} placeholder="Example: Karnataka" /></label><div className="form-actions"><Button variant="primary" type="submit" disabled={busy}>{busy ? 'Saving…' : editingId ? 'Update supplier' : 'Add supplier'}</Button></div></form></FormSheet>}</div>
}
